### ISSUE TITLE
Why is CUDA not *much* faster then CPU?

### ISSUE THREAD

**Issue by coveritytest** [danielgatis/rembg#75] opened 2021-02-06 16:35 UTC
I ran `rembg -o 01.PNG 01.JPG` on a system with CUDA support and on a system without CUDA support. It's a 2784x1856 JPG with  3.32 MB. CUDA is 11 seconds, CPU is 14 seconds. CUDA is actually used as the check in https://github.com/danielgatis/rembg/blob/master/src/rembg/u2net/detect.py#L92 is successful. Can you explain that to me please?

**Comment by ecsplendid** [comment] 2021-02-06 17:28
Yes I would like to know too, I get pretty much zero GPU utilization when converting a folder. I get about 11 images per second on GPU and about 2-3 per second on CPU. Without digging into the code I would imagine the problem is with IO i.e. should be batching in the images and doing a single pass through the GPU but that's not happening

**Comment by coveritytest** [comment] 2021-02-06 17:40
Okay, but thats a lot faster then on my system. How many pixels and what size do your pictures have?

**Comment by ecsplendid** [comment] 2021-02-06 17:52
It should not matter because the DNN expects 300^2^3 I think and he resizes it to that before passing in. You can probably save in IO/CPU time by making your images small before going in and not bothering with the post processing stuff (the alpha masking etc). 

I am looking at the predict function now in detect.py, I am pretty sure this is the bottleneck for doing many images (I am doing about 200K images all at once, for video), the model can take in a batch but we are doing a pass one image at a time. I think there is potential for a massive speedup here

**Comment by coveritytest** [comment] 2021-02-06 18:57
Yes, you're right, a 69 KB jpg takes 8 seconds. I'm pretty sure, the GPU is not really involved at all, as the task manager in Windows 10 says the load is 0% to 1% while analysing 1100 pictures. It averages to about 6 seconds per iteration.

**Comment by ecsplendid** [comment] 2021-02-06 19:01
Yes, I assume it's "not involved" because the program is currently CPU-bound i.e. loading the image, resizing it etc takes longer than the GPU operation. The DNN does actually expect a batch of images (he is doing unsqueeze(0) to make it take just one image), so it should be easy to fix this. I am playing with it, been a while since I did any Python though.

**Comment by coveritytest** [comment] 2021-02-06 19:16
Okay I see, great to hear!

**Comment by ecsplendid** [comment] 2021-02-06 23:57
Been playing a bit, it's not great news so far -- I can predict with a larger input i.e. 

```
images = np.zeros( (4, 3, 320, 320) )
```

Which has a batch of 4, my 2800GTX with about 11gb ram runs out around 6-7 input images (first dimension). This is a monster model, still worth seeing what increase of throughput this gives us though, if any. The CPU operations are going to be commensurately expensive so this might be a wasted effort

**Comment by ecsplendid** [comment] 2021-02-07 02:38
![image](https://user-images.githubusercontent.com/6911390/107134617-a339a780-68eb-11eb-8a44-19e14fcf195f.png)

I am now getting nearly 30 images/second which is about 3 times faster

Still not exactly brilliant utilisation of my machine;
![image](https://user-images.githubusercontent.com/6911390/107134631-b9dffe80-68eb-11eb-9836-ff38300a5117.png)
![image](https://user-images.githubusercontent.com/6911390/107134636-c1070c80-68eb-11eb-9ade-1e5e1e234c10.png)

Here is the code -- needs a bit of cleanup it's currently forcing square aspect
https://github.com/ecsplendid/rembg/commit/2c8f0311d35817c98d49b6bfd8fd4e8b307fc8e2

I noticed I can actually set a higher batch size i.e. up to about 25 but it runs faster on ~10!

**Comment by ecsplendid** [comment] 2021-02-07 03:56
Also the behaviour of mine is slightly different 

![image](https://user-images.githubusercontent.com/6911390/107136108-4abcd700-68f8-11eb-99e1-e1739b996aa2.png)

I am pretty sure I am doing exactly the same steps on normalisation, other than averaging over more images

**Comment by ecsplendid** [comment] 2021-02-07 12:33
I've just been brainstorming the architecture, i.e. what would happen if we had a batching step on CPU with normalisation etc first. I think we are pretty stuck really. Most of the time is spend on disc IO and processing the images in CPU. We can't do anything about the disk IO i.e. at some point we have to read and write from the disk. 

btw I have noticed the results are significantly faster if you pass in small images i.e. as close to 320 as possible and then better if you use small BMPs as inputs, JPG is quite crap at that scale and the segmentation suffers. I have also noticed there is a human trained segmentation model from the same authors which works WAY better for my green screen purposes. 

This is my mindmap of the performance pipeline -- 
![image](https://user-images.githubusercontent.com/6911390/107146476-7794dc80-6940-11eb-9529-31e3ee9232c9.png)

We can experiment with dropping some of the CPU stuff i.e. cutouts and processing. For my purposes (green screening) I only need the cutout anyway. I think my "batching on CPU" idea was flawed for reasons given above i.e. at some point you have to do it, doesn't matter if you group the operations together

**Comment by ecsplendid** [comment] 2021-02-07 13:29
Now tested the CPU stuff, this thing is almost entirely disk bound. So the solution for green screen is to use https://zulko.github.io/moviepy/getting_started/videoclips.html and stream the frames entirely in memory

**Comment by coveritytest** [comment] 2021-02-07 16:29
Thanks for you work, will try this soon.

**Comment by ecsplendid** [comment] 2021-02-08 01:33
I implemented the code to stream it directly into FFMPEG on my fork, no image files written to disk -- it's still bottlenecked though, but a really clean one-liner for making green screen mattes 

Profiled it

![image](https://user-images.githubusercontent.com/6911390/107166290-78178c80-69ad-11eb-90ae-f89535a34b81.png)

One expensive list comp I can defo fix, but no low hanging fruit there really

**Comment by ecsplendid** [comment] 2021-02-08 12:59
Made this video and updated the readme on my fork

https://share.descript.com/view/YTo9QAZU5EC

https://github.com/ecsplendid/rembg

**Comment by danielgatis** [comment] 2021-02-08 13:14
> Made this video and updated the readme on my fork
> 
> https://share.descript.com/view/YTo9QAZU5EC
> 
> https://github.com/ecsplendid/rembg

@ecsplendid wow! nice work!

**Comment by JuMayr** [comment] 2021-02-08 14:29
I really admire this project, but i am not a dev (not even close to). 
What i can offer is a testrun on my Hardware if you want to do a Teamviewer session. 
AMD Threadripper 3960X 24Core
PCIe 4.0 M2 SSD with 7000/5000MB
GFORCE RTX 3080

If this helps in any way to narrow down the bottleneck, i am happy to help. 

![grafik](https://user-images.githubusercontent.com/16525908/107232920-4a205f80-6a22-11eb-9174-19100f17b8e9.png)

**Comment by ecsplendid** [comment] 2021-02-09 00:43
I checked in an experimental parallel processing version into my fork

![image](https://user-images.githubusercontent.com/6911390/107299642-c725f600-6a6f-11eb-8a67-d22c80a383a8.png)

![image](https://user-images.githubusercontent.com/6911390/107299653-cc834080-6a6f-11eb-8c4b-e11a2eb308f2.png)

Updated readme too, copy the uncompressed data between workers is killing perf, but there are some things we can do to tweak

**Comment by mnayef95** [comment] 2021-02-10 17:05
@ecsplendid Can we use your repo with images instead of video? if yes could you please give an example?

**Comment by ecsplendid** [comment] 2021-02-10 20:56
> @ecsplendid Can we use your repo with images instead of video? if yes could you please give an example?

Sorry I took it out of my version, it's just generating mono video mattes

**Comment by ecsplendid** [comment] 2021-02-15 16:20
Made a few improvements over on my fork -- here is a video demo https://www.youtube.com/watch?v=4NjqR2vCV_k

**Comment by coveritytest** [comment] 2021-02-28 07:23
@ecsplendid Would be great, if you could do this with images instead of video :)

**Comment by danielgatis** [comment] 2021-03-27 14:09
I added a link on readme for this great work. congrats @ecsplendid.

**Closed by danielgatis** 2021-03-27 14:09 UTC
